<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\Banner
 *
 * 广告管理
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\BannerRepository")
 * @ORM\Table(name="banner")
 */
class Banner
{
	/**
	 * 主键ID
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * 文件名字
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $filename;

	/**
	 * http  Url
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $url;

	/**
	 * 备注
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $mark;

	/**
	 * 创建时间
	 *
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $created_at;

	/**
	 * 更新时间
	 *
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $updated_at;

	public function __construct()
	{
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of filename.
	 *
	 * @param string $filename
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setFilename($filename)
	{
		$this->filename = $filename;

		return $this;
	}

	/**
	 * Get the value of filename.
	 *
	 * @return string
	 */
	public function getFilename()
	{
		return $this->filename;
	}

	/**
	 * Set the value of url.
	 *
	 * @param string $url
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setUrl($url)
	{
		$this->url = $url;

		return $this;
	}

	/**
	 * Get the value of url.
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set the value of mark.
	 *
	 * @param string $mark
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setMark($mark)
	{
		$this->mark = $mark;

		return $this;
	}

	/**
	 * Get the value of mark.
	 *
	 * @return string
	 */
	public function getMark()
	{
		return $this->mark;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param int $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return int
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param int $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\Banner
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return int
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	public function __sleep()
	{
		return array('id', 'filename', 'url', 'mark', 'created_at', 'updated_at');
	}
}