<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * WeiXin\Entity\Mapping\Category
 *
 * 分类表
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\CategoryRepository")
 * @ORM\Table(name="category")
 */
class Category
{
    /**
     * 主键
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 名字
     *
     * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected $name;

    /**
     * 父级ID
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $parent_id;

    /**
     * 路径
     *
     * @ORM\Column(name="`path`", type="string", length=255, nullable=true)
     */
    protected $path;

    /**
     * 扩展字段
     *
     * @ORM\Column(type="json", nullable=true)
     */
    protected $ext = '{}';

    /**
     * 创建时间
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $created_at;

    /**
     * 更新时间
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $updated_at;

    public function __construct()
    {
        $this->news = new ArrayCollection();
        $this->scenic_spot_plans = new ArrayCollection();
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return Category
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     *
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of parent_id.
     *
     * @return int
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Set the value of parent_id.
     *
     * @param int $parent_id
     *
     * @return Category
     */
    public function setParentId($parent_id)
    {
        $this->parent_id = $parent_id;

        return $this;
    }

    /**
     * Get the value of path.
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set the value of path.
     *
     * @param string $path
     *
     * @return Category
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get the value of ext.
     *
     * @return array
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * Set the value of ext.
     *
     * @param array $ext
     *
     * @return Category
     */
    public function setExt($ext)
    {
        $this->ext = $ext;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of created_at.
     *
     * @param int $created_at
     *
     * @return Category
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return int
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param int $updated_at
     *
     * @return Category
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function __sleep()
    {
        return array('id', 'name', 'parent_id', 'path', 'ext', 'created_at', 'updated_at');
    }
}