<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * WeiXin\Entity\Mapping\News
 *
 * 新闻表
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\NewsRepository")
 * @ORM\Table(name="news", indexes={@ORM\Index(name="fk_news_category1_idx", columns={"category_id"})})
 */
class News
{
    /**
     * 主键
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected int $id;

    /**
     * 分类
     *
     * @ORM\Column(name="`category_id`", type="integer")
     */
    protected int $categoryId;

    /**
     * 名字
     *
     * @ORM\Column(name="`title`", type="string", length=45, nullable=true)
     */
    protected string $title;

    /**
     * 关键字
     *
     * @ORM\Column(name="`keywords`" , type="string", length=45, nullable=true)
     */
    protected string $keywords;

    /**
     * 内容
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected string $content;

    /**
     * 创建时间
     *
     * @ORM\Column(name="`created_at`" , type="integer", nullable=true)
     */
    protected int $createdAt;

    /**
     * 更新时间
     *
     * @ORM\Column(name="`updated_at`" , type="integer", nullable=true)
     */
    protected int $updatedAt;

    /**
     * 扩展数据
     * @ORM\Column(type="json", nullable=true)
     */
    protected array $ext;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getCategoryId(): int
    {
        return $this->categoryId;
    }

    /**
     * @param int $categoryId
     */
    public function setCategoryId(int $categoryId): void
    {
        $this->categoryId = $categoryId;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getKeywords(): string
    {
        return $this->keywords;
    }

    /**
     * @param string $keywords
     */
    public function setKeywords(string $keywords): void
    {
        $this->keywords = $keywords;
    }

    /**
     * @return string
     */
    public function getContent(): string
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent(string $content): void
    {
        $this->content = $content;
    }

    /**
     * @return int
     */
    public function getCreatedAt(): int
    {
        return $this->createdAt;
    }

    /**
     * @param int $createdAt
     */
    public function setCreatedAt(int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return int
     */
    public function getUpdatedAt(): int
    {
        return $this->updatedAt;
    }

    /**
     * @param int $updatedAt
     */
    public function setUpdatedAt(int $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return array
     */
    public function getExt(): array
    {
        return $this->ext;
    }

    /**
     * @param array $ext
     */
    public function setExt(array $ext): void
    {
        $this->ext = $ext;
    }

    public function __sleep()
    {
        return array('id', 'categoryId', 'name', 'keywords', 'content', 'createdAt', 'updatedAt');
    }
}