<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * WeiXin\Entity\Mapping\News
 *
 * 新闻表
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\NewsRepository")
 * @ORM\Table(name="news", indexes={@ORM\Index(name="fk_news_category1_idx", columns={"category_id"})})
 */
class News
{
    /**
     * 主键
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 分类
     *
     * @ORM\Column(type="integer")
     */
    protected $category_id;

    /**
     * 名字
     *
     * @ORM\Column(name="`title`", type="string", length=45, nullable=true)
     */
    protected $title;

    /**
     * 关键字
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $keywords;

    /**
     * 内容
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $content;

    /**
     * 创建时间
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $created_at;

    /**
     * 更新时间
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $updated_at;

    /**
     * 扩展数据
     * @ORM\Column(type="json", nullable=true)
     */
    protected $ext;

    /**
     * @ORM\ManyToOne(targetEntity="WeiXin\Entity\Mapping\Category", inversedBy="news")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", nullable=false)
     */
    protected $category;

    public function __construct()
    {
    }

    /**
     * Get the value of id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of id.
     *
     * @param int $id
     *
     * @return News
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * @param mixed $ext
     */
    public function setExt($ext): void
    {
        $this->ext = $ext;
    }

    /**
     * Get the value of category_id.
     *
     * @return int
     */
    public function getCategoryId()
    {
        return $this->category_id;
    }

    /**
     * Set the value of category_id.
     *
     * @param int $category_id
     *
     * @return News
     */
    public function setCategoryId($category_id)
    {
        $this->category_id = $category_id;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set the value of name.
     *
     * @param string $title
     *
     * @return News
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get the value of keywords.
     *
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Set the value of keywords.
     *
     * @param string $keywords
     *
     * @return News
     */
    public function setKeywords($keywords)
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Get the value of content.
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set the value of content.
     *
     * @param string $content
     *
     * @return News
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get the value of created_at.
     *
     * @return int
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set the value of created_at.
     *
     * @param int $created_at
     *
     * @return News
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * Get the value of updated_at.
     *
     * @return int
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Set the value of updated_at.
     *
     * @param int $updated_at
     *
     * @return News
     */
    public function setUpdatedAt($updated_at)
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * Get Category entity (many to one).
     *
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set Category entity (many to one).
     *
     * @param Category $category
     *
     * @return News
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    public function __sleep()
    {
        return array('id', 'category_id', 'name', 'keywords', 'content', 'created_at', 'updated_at');
    }
}