<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\ResourceManagement
 *
 * 资源管理表
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\ResourceManagementRepository")
 * @ORM\Table(name="resource_management")
 */
class ResourceManagement
{
	/**
	 * 主键
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * 目标ID
	 *
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $target_id;

	/**
	 * URL
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $url;

	/**
	 * 名字
	 *
	 * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
	 */
	protected $name;

	/**
	 * 大小
	 *
	 * @ORM\Column(name="`size`", type="integer", nullable=true)
	 */
	protected $size;

	/**
	 * 类型:
	 * 1 景区缩略图
	 * 2 景区轮播图
	 * 3 ....
	 *
	 * @ORM\Column(name="`type`", type="smallint", nullable=true)
	 */
	protected $type;

	/**
	 * 创建时间
	 *
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $created_at;

	/**
	 * 更新时间
	 *
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $updated_at;

	public function __construct()
	{
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of target_id.
	 *
	 * @param int $target_id
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setTargetId($target_id)
	{
		$this->target_id = $target_id;

		return $this;
	}

	/**
	 * Get the value of target_id.
	 *
	 * @return int
	 */
	public function getTargetId()
	{
		return $this->target_id;
	}

	/**
	 * Set the value of url.
	 *
	 * @param string $url
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setUrl($url)
	{
		$this->url = $url;

		return $this;
	}

	/**
	 * Get the value of url.
	 *
	 * @return string
	 */
	public function getUrl()
	{
		return $this->url;
	}

	/**
	 * Set the value of name.
	 *
	 * @param string $name
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * Get the value of name.
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set the value of size.
	 *
	 * @param int $size
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setSize($size)
	{
		$this->size = $size;

		return $this;
	}

	/**
	 * Get the value of size.
	 *
	 * @return int
	 */
	public function getSize()
	{
		return $this->size;
	}

	/**
	 * Set the value of type.
	 *
	 * @param int $type
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setType($type)
	{
		$this->type = $type;

		return $this;
	}

	/**
	 * Get the value of type.
	 *
	 * @return int
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param int $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return int
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param int $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\ResourceManagement
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return int
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	public function __sleep()
	{
		return array('id', 'target_id', 'url', 'name', 'size', 'type', 'created_at', 'updated_at');
	}
}