<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\ScenicArea
 *
 * 景区
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\ScenicAreaRepository")
 * @ORM\Table(name="scenic_area")
 */
class ScenicArea
{
	/**
	 * 主键ID
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * 名字
	 *
	 * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
	 */
	protected $name;

	/**
	 * 价格
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $price;

	/**
	 * @ORM\Column(type="array", nullable=true)
	 */
	protected $ext;

	/**
	 * 省
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $province;

	/**
	 * 市
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $city;

	/**
	 * 区
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $area;

	/**
	 * 电话
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $tel;

	/**
	 * 地址
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $address;

	/**
	 * 简介
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $synopsis;

	/**
	 * 详情
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $detail;

	/**
	 * 创建时间
	 *
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $created_at;

	/**
	 * 更新时间
	 *
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $updated_at;

	/**
	 * @ORM\OneToMany(targetEntity="WeiXin\Entity\Mapping\ScenicSpotAreaRelation", mappedBy="scenic_area")
	 * @ORM\JoinColumn(name="id", referencedColumnName="scenic_area_id", nullable=false)
	 */
	protected $scenic_spot_area_relations;

	/**
	 * @ORM\ManyToMany(targetEntity="WeiXin\Entity\Mapping\ScenicSpotPlan", inversedBy="scenic_areas")
	 * @ORM\JoinTable(name="scenic_spot_area_relation",
	 *     joinColumns={@ORM\JoinColumn(name="scenic_area_id", referencedColumnName="id", nullable=false)},
	 *     inverseJoinColumns={@ORM\JoinColumn(name="scenic_spot_plan_id", referencedColumnName="id", nullable=false)}
	 * )
	 */
	protected $scenic_spot_plans;

	public function __construct()
	{
		$this->scenic_spot_area_relations = new ArrayCollection();
		$this->scenic_spot_plans = new ArrayCollection();
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of name.
	 *
	 * @param string $name
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * Get the value of name.
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set the value of price.
	 *
	 * @param string $price
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setPrice($price)
	{
		$this->price = $price;

		return $this;
	}

	/**
	 * Get the value of price.
	 *
	 * @return string
	 */
	public function getPrice()
	{
		return $this->price;
	}

	/**
	 * Set the value of ext.
	 *
	 * @param array $ext
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setExt($ext)
	{
		$this->ext = $ext;

		return $this;
	}

	/**
	 * Get the value of ext.
	 *
	 * @return array
	 */
	public function getExt()
	{
		return $this->ext;
	}

	/**
	 * Set the value of province.
	 *
	 * @param string $province
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setProvince($province)
	{
		$this->province = $province;

		return $this;
	}

	/**
	 * Get the value of province.
	 *
	 * @return string
	 */
	public function getProvince()
	{
		return $this->province;
	}

	/**
	 * Set the value of city.
	 *
	 * @param string $city
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setCity($city)
	{
		$this->city = $city;

		return $this;
	}

	/**
	 * Get the value of city.
	 *
	 * @return string
	 */
	public function getCity()
	{
		return $this->city;
	}

	/**
	 * Set the value of area.
	 *
	 * @param string $area
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setArea($area)
	{
		$this->area = $area;

		return $this;
	}

	/**
	 * Get the value of area.
	 *
	 * @return string
	 */
	public function getArea()
	{
		return $this->area;
	}

	/**
	 * Set the value of tel.
	 *
	 * @param string $tel
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setTel($tel)
	{
		$this->tel = $tel;

		return $this;
	}

	/**
	 * Get the value of tel.
	 *
	 * @return string
	 */
	public function getTel()
	{
		return $this->tel;
	}

	/**
	 * Set the value of address.
	 *
	 * @param string $address
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setAddress($address)
	{
		$this->address = $address;

		return $this;
	}

	/**
	 * Get the value of address.
	 *
	 * @return string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Set the value of synopsis.
	 *
	 * @param string $synopsis
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setSynopsis($synopsis)
	{
		$this->synopsis = $synopsis;

		return $this;
	}

	/**
	 * Get the value of synopsis.
	 *
	 * @return string
	 */
	public function getSynopsis()
	{
		return $this->synopsis;
	}

	/**
	 * Set the value of detail.
	 *
	 * @param string $detail
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setDetail($detail)
	{
		$this->detail = $detail;

		return $this;
	}

	/**
	 * Get the value of detail.
	 *
	 * @return string
	 */
	public function getDetail()
	{
		return $this->detail;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param string $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return string
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param string $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return string
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	/**
	 * Add ScenicSpotAreaRelation entity to collection (one to many).
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicSpotAreaRelation $scenic_spot_area_relation
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function addScenicSpotAreaRelation($scenic_spot_area_relation)
	{
		$this->scenic_spot_area_relations[] = $scenic_spot_area_relation;

		return $this;
	}

	/**
	 * Remove ScenicSpotAreaRelation entity from collection (one to many).
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicSpotAreaRelation $scenic_spot_area_relation
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function removeScenicSpotAreaRelation($scenic_spot_area_relation)
	{
		$this->scenic_spot_area_relations->removeElement($scenic_spot_area_relation);

		return $this;
	}

	/**
	 * Get ScenicSpotAreaRelation entity collection (one to many).
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getScenicSpotAreaRelations()
	{
		return $this->scenic_spot_area_relations;
	}

	/**
	 * Add ScenicSpotPlan entity to collection.
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicSpotPlan $scenic_spot_plan
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function addScenicSpotPlan($scenic_spot_plan)
	{
		$scenic_spot_plan->addScenicArea($this);
		$this->scenic_spot_plans[] = $scenic_spot_plan;

		return $this;
	}

	/**
	 * Remove ScenicSpotPlan entity from collection.
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicSpotPlan $scenic_spot_plan
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function removeScenicSpotPlan($scenic_spot_plan)
	{
		$scenic_spot_plan->removeScenicArea($this);
		$this->scenic_spot_plans->removeElement($ScenicSpotPlan);

		return $this;
	}

	/**
	 * Get ScenicSpotPlan entity collection.
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getScenicSpotPlans()
	{
		return $this->scenic_spot_plans;
	}

	public function __sleep()
	{
		return array('id', 'name', 'price', 'ext', 'province', 'city', 'area', 'tel', 'address', 'synopsis', 'detail', 'created_at', 'updated_at');
	}
}