<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\ScenicSpotAreaRelation
 *
 * 景区套餐关系表
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\ScenicSpotAreaRelationRepository")
 * @ORM\Table(name="scenic_spot_area_relation", indexes={@ORM\Index(name="fk_scenic_spot_plan_has_scenic_area_scenic_area1_idx", columns={"scenic_area_id"}), @ORM\Index(name="fk_scenic_spot_plan_has_scenic_area_scenic_spot_plan1_idx", columns={"scenic_spot_plan_id"})})
 */
class ScenicSpotAreaRelation
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 */
	protected $scenic_spot_plan_id;

	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 */
	protected $scenic_area_id;

	/**
	 * @ORM\ManyToOne(targetEntity="WeiXin\Entity\Mapping\ScenicSpotPlan", inversedBy="scenic_spot_area_relations")
	 * @ORM\JoinColumn(name="scenic_spot_plan_id", referencedColumnName="id", nullable=false)
	 */
	protected $scenic_spot_plan;

	/**
	 * @ORM\ManyToOne(targetEntity="WeiXin\Entity\Mapping\ScenicArea", inversedBy="scenic_spot_area_relations")
	 * @ORM\JoinColumn(name="scenic_area_id", referencedColumnName="id", nullable=false)
	 */
	protected $scenic_area;

	public function __construct()
	{
	}

	/**
	 * Set the value of scenic_spot_plan_id.
	 *
	 * @param int $scenic_spot_plan_id
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicSpotAreaRelation
	 */
	public function setScenicSpotPlanId($scenic_spot_plan_id)
	{
		$this->scenic_spot_plan_id = $scenic_spot_plan_id;

		return $this;
	}

	/**
	 * Get the value of scenic_spot_plan_id.
	 *
	 * @return int
	 */
	public function getScenicSpotPlanId()
	{
		return $this->scenic_spot_plan_id;
	}

	/**
	 * Set the value of scenic_area_id.
	 *
	 * @param int $scenic_area_id
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicSpotAreaRelation
	 */
	public function setScenicAreaId($scenic_area_id)
	{
		$this->scenic_area_id = $scenic_area_id;

		return $this;
	}

	/**
	 * Get the value of scenic_area_id.
	 *
	 * @return int
	 */
	public function getScenicAreaId()
	{
		return $this->scenic_area_id;
	}

	/**
	 * Set ScenicSpotPlan entity (many to one).
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicSpotPlan $scenic_spot_plan
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicSpotAreaRelation
	 */
	public function setScenicSpotPlan($scenic_spot_plan)
	{
		$this->scenic_spot_plan = $ScenicSpotPlan;

		return $this;
	}

	/**
	 * Get ScenicSpotPlan entity (many to one).
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicSpotPlan
	 */
	public function getScenicSpotPlan()
	{
		return $this->scenic_spot_plan;
	}

	/**
	 * Set ScenicArea entity (many to one).
	 *
	 * @param \WeiXin\Entity\Mapping\ScenicArea $scenic_area
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicSpotAreaRelation
	 */
	public function setScenicArea($scenic_area)
	{
		$this->scenic_area = $ScenicArea;

		return $this;
	}

	/**
	 * Get ScenicArea entity (many to one).
	 *
	 * @return \WeiXin\Entity\Mapping\ScenicArea
	 */
	public function getScenicArea()
	{
		return $this->scenic_area;
	}

	public function __sleep()
	{
		return array('scenic_spot_plan_id', 'scenic_area_id');
	}
}