<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\ScenicSpotPlan
 *
 * 景区套餐
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\ScenicSpotPlanRepository")
 * @ORM\Table(name="scenic_spot_plan", indexes={@ORM\Index(name="fk_scenic_spot_plan_category1_idx", columns={"category_id"})})
 */
class ScenicSpotPlan
{
	/**
	 * 主键
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 */
	protected int $id;

	/**
	 * 分类ID
	 *
	 * @ORM\Column(name="`category_id`", type="integer")
	 */
	protected int $categoryId;

	/**
	 * 套餐名字
	 *
	 * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
	 */
	protected string $name;

	/**
	 * 套餐价格
	 *
	 * @ORM\Column(type="integer", length=11, nullable=true)
	 */
	protected string $price;

	/**
	 * 套餐描述
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected string $synopsis;

	/**
	 * 套餐详情
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected string $detail;

	/**
	 * 状态:
	 * 0 停用
	 * 1 正常
	 *
	 * @ORM\Column(name="`status`", type="smallint", nullable=true)
	 */
	protected int $status;

	/**
	 * 扩展字段
	 *
	 * @ORM\Column(type="json", nullable=true)
	 */
	protected array $ext;

	/**
	 * 创建时间
	 *
	 * @ORM\Column(name="`created_at`" , type="integer", nullable=true)
	 */
	protected int $createdAt;

	/**
	 * 更新时间
	 *
	 * @ORM\Column(name="`updated_at`" , type="integer", nullable=true)
	 */
	protected int $updatedAt;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return int
     */
    public function getCategoryId(): int
    {
        return $this->categoryId;
    }

    /**
     * @param int $categoryId
     */
    public function setCategoryId(int $categoryId): void
    {
        $this->categoryId = $categoryId;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getPrice(): string
    {
        return $this->price;
    }

    /**
     * @param string $price
     */
    public function setPrice(string $price): void
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getSynopsis(): string
    {
        return $this->synopsis;
    }

    /**
     * @param string $synopsis
     */
    public function setSynopsis(string $synopsis): void
    {
        $this->synopsis = $synopsis;
    }

    /**
     * @return string
     */
    public function getDetail(): string
    {
        return $this->detail;
    }

    /**
     * @param string $detail
     */
    public function setDetail(string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return array
     */
    public function getExt(): array
    {
        return $this->ext;
    }

    /**
     * @param array $ext
     */
    public function setExt(array $ext): void
    {
        $this->ext = $ext;
    }

    /**
     * @return int
     */
    public function getCreatedAt(): int
    {
        return $this->createdAt;
    }

    /**
     * @param int $createdAt
     */
    public function setCreatedAt(int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return int
     */
    public function getUpdatedAt(): int
    {
        return $this->updatedAt;
    }

    /**
     * @param int $updatedAt
     */
    public function setUpdatedAt(int $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

	public function __sleep()
	{
		return array('id', 'categoryId', 'name', 'price', 'synopsis', 'detail', 'status', 'ext', 'createdAt', 'updatedAt');
	}
}