<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * WeiXin\Entity\Mapping\ScenicArea
 *
 * 景区
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\ScenicAreaRepository")
 * @ORM\Table(name="scenic_area")
 */
class ScenicArea
{
    /**
     * 主键ID
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected int $id;

    /**
     * 名字
     *
     * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected string $name;

    /**
     * 价格
     *
     * @ORM\Column(type="integer", length=45, nullable=true)
     */
    protected string $price;

    /**
     * @ORM\Column(name="`ext`" , type="json", nullable=true)
     */
    protected array $ext;

    /**
     * 省
     *
     * @ORM\Column(type="integer", length=45, nullable=true)
     */
    protected int $province;

    /**
     * 市
     *
     * @ORM\Column(type="integer", length=45, nullable=true)
     */
    protected int $city;

    /**
     * 区
     *
     * @ORM\Column(type="integer", length=45, nullable=true)
     */
    protected int $area;

    /**
     * 电话
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $tel;

    /**
     * 地址
     *
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    protected string $address;

    /**
     * 简介
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $synopsis;

    /**
     * 详情
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $detail;

    /**
     * 创建时间
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="integer", length=45, nullable=true)
     */
    protected int $createdAt;

    /**
     * 更新时间
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $updatedAt;

    public function __construct()
    {
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getPrice(): string
    {
        return $this->price;
    }

    /**
     * @param string $price
     */
    public function setPrice(string $price): void
    {
        $this->price = $price;
    }

    /**
     * @return array
     */
    public function getExt(): array
    {
        return $this->ext;
    }

    /**
     * @param array $ext
     */
    public function setExt(array $ext): void
    {
        $this->ext = $ext;
    }

    /**
     * @return int
     */
    public function getProvince(): int
    {
        return $this->province;
    }

    /**
     * @param int $province
     */
    public function setProvince(int $province): void
    {
        $this->province = $province;
    }

    /**
     * @return int
     */
    public function getCity(): int
    {
        return $this->city;
    }

    /**
     * @param int $city
     */
    public function setCity(int $city): void
    {
        $this->city = $city;
    }

    /**
     * @return int
     */
    public function getArea(): int
    {
        return $this->area;
    }

    /**
     * @param int $area
     */
    public function setArea(int $area): void
    {
        $this->area = $area;
    }

    /**
     * @return string
     */
    public function getTel(): string
    {
        return $this->tel;
    }

    /**
     * @param string $tel
     */
    public function setTel(string $tel): void
    {
        $this->tel = $tel;
    }

    /**
     * @return string
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * @param string $address
     */
    public function setAddress(string $address): void
    {
        $this->address = $address;
    }

    /**
     * @return string
     */
    public function getSynopsis(): string
    {
        return $this->synopsis;
    }

    /**
     * @param string $synopsis
     */
    public function setSynopsis(string $synopsis): void
    {
        $this->synopsis = $synopsis;
    }

    /**
     * @return string
     */
    public function getDetail(): string
    {
        return $this->detail;
    }

    /**
     * @param string $detail
     */
    public function setDetail(string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * @return int
     */
    public function getCreatedAt(): int
    {
        return $this->createdAt;
    }

    /**
     * @param int $createdAt
     */
    public function setCreatedAt(int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return string
     */
    public function getUpdatedAt(): string
    {
        return $this->updatedAt;
    }

    /**
     * @param string $updatedAt
     */
    public function setUpdatedAt(string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function __sleep()
    {
        return array('id', 'name', 'price', 'ext', 'province', 'city', 'area', 'tel', 'address', 'synopsis', 'detail', 'created_at', 'updated_at');
    }
}