<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\SignUp
 *
 * 报名
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\SignUpRepository")
 * @ORM\Table(name="sign_up")
 */
class SignUp
{
	/**
	 * 主键
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * 名称
	 *
	 * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
	 */
	protected $name;

	/**
	 * 电话
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $phone;

	/**
	 * 身份证号
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $idCard;

	/**
	 * 扩展字段
	 *
	 * @ORM\Column(type="array", nullable=true)
	 */
	protected $ext;

	/**
	 * 创建时间
	 *
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $created_at;

	/**
	 * 更新时间
	 *
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $updated_at;

	public function __construct()
	{
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of name.
	 *
	 * @param string $name
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setName($name)
	{
		$this->name = $name;

		return $this;
	}

	/**
	 * Get the value of name.
	 *
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set the value of phone.
	 *
	 * @param string $phone
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setPhone($phone)
	{
		$this->phone = $phone;

		return $this;
	}

	/**
	 * Get the value of phone.
	 *
	 * @return string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Set the value of idCard.
	 *
	 * @param string $idCard
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setIdCard($idCard)
	{
		$this->idCard = $idCard;

		return $this;
	}

	/**
	 * Get the value of idCard.
	 *
	 * @return string
	 */
	public function getIdCard()
	{
		return $this->idCard;
	}

	/**
	 * Set the value of ext.
	 *
	 * @param array $ext
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setExt($ext)
	{
		$this->ext = $ext;

		return $this;
	}

	/**
	 * Get the value of ext.
	 *
	 * @return array
	 */
	public function getExt()
	{
		return $this->ext;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param int $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return int
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param int $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\SignUp
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return int
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	public function __sleep()
	{
		return array('id', 'name', 'phone', 'idCard', 'ext', 'created_at', 'updated_at');
	}
}