<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * WeiXin\Entity\Mapping\SignUp
 *
 * 报名
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\SignUpRepository")
 * @ORM\Table(name="sign_up")
 */
class SignUp
{
    /**
     * 主键
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected int $id;

    /**
     * 名称
     *
     * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected string $name;

    /**
     * 电话
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $phone;

    /**
     * 身份证号
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected string $idCard;

    /**
     * 扩展字段
     *
     * @ORM\Column(type="json", nullable=true)
     */
    protected array $ext;

    /**
     * 创建时间
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="`created_at`" , "type="integer", nullable=true)
     */
    protected int $createdAt;

    /**
     * 更新时间
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="`updated_at`","type="integer", nullable=true)
     */
    protected int $updatedAt;

    public function __construct()
    {
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getPhone(): string
    {
        return $this->phone;
    }

    /**
     * @param string $phone
     */
    public function setPhone(string $phone): void
    {
        $this->phone = $phone;
    }

    /**
     * @return string
     */
    public function getIdCard(): string
    {
        return $this->idCard;
    }

    /**
     * @param string $idCard
     */
    public function setIdCard(string $idCard): void
    {
        $this->idCard = $idCard;
    }

    /**
     * @return array
     */
    public function getExt(): array
    {
        return $this->ext;
    }

    /**
     * @param array $ext
     */
    public function setExt(array $ext): void
    {
        $this->ext = $ext;
    }

    /**
     * @return int
     */
    public function getCreatedAt(): int
    {
        return $this->createdAt;
    }

    /**
     * @param int $createdAt
     */
    public function setCreatedAt(int $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return int
     */
    public function getUpdatedAt(): int
    {
        return $this->updatedAt;
    }

    /**
     * @param int $updatedAt
     */
    public function setUpdatedAt(int $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    public function __sleep()
    {
        return array('id', 'name', 'phone', 'idCard', 'ext', 'createdAt', 'updatedAt');
    }
}