<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\User
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\UserRepository")
 * @ORM\Table(name="users")
 */
class User
{
	/**
	 * 主键
	 *
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * 用户名
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $username;

	/**
	 * 密码
	 *
	 * @ORM\Column(name="`password`", type="string", length=45, nullable=true)
	 */
	protected $password;

	/**
	 * openId
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $open_id;

	/**
	 * 电话号码
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $phone;

	/**
	 * 身份证号
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $idCard;

	/**
	 * 昵称
	 *
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $nickname;

	/**
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $created_at;

	/**
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $updated_at;

	/**
	 * @ORM\OneToOne(targetEntity="WeiXin\Entity\Mapping\UserProfile", mappedBy="users")
	 */
	protected $user_profile;

	public function __construct()
	{
		$this->user_profiles = new ArrayCollection();
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of username.
	 *
	 * @param string $username
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setUsername($username)
	{
		$this->username = $username;

		return $this;
	}

	/**
	 * Get the value of username.
	 *
	 * @return string
	 */
	public function getUsername()
	{
		return $this->username;
	}

	/**
	 * Set the value of password.
	 *
	 * @param string $password
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setPassword($password)
	{
		$this->password = $password;

		return $this;
	}

	/**
	 * Get the value of password.
	 *
	 * @return string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Set the value of open_id.
	 *
	 * @param string $open_id
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setOpenId($open_id)
	{
		$this->open_id = $open_id;

		return $this;
	}

	/**
	 * Get the value of open_id.
	 *
	 * @return string
	 */
	public function getOpenId()
	{
		return $this->open_id;
	}

	/**
	 * Set the value of phone.
	 *
	 * @param string $phone
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setPhone($phone)
	{
		$this->phone = $phone;

		return $this;
	}

	/**
	 * Get the value of phone.
	 *
	 * @return string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Set the value of idCard.
	 *
	 * @param string $idCard
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setIdCard($idCard)
	{
		$this->idCard = $idCard;

		return $this;
	}

	/**
	 * Get the value of idCard.
	 *
	 * @return string
	 */
	public function getIdCard()
	{
		return $this->idCard;
	}

	/**
	 * Set the value of nickname.
	 *
	 * @param string $nickname
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setNickname($nickname)
	{
		$this->nickname = $nickname;

		return $this;
	}

	/**
	 * Get the value of nickname.
	 *
	 * @return string
	 */
	public function getNickname()
	{
		return $this->nickname;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param int $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return int
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param int $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return int
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	/**
	 * Set UserProfile entity (one to one).
	 *
	 * @param \WeiXin\Entity\Mapping\UserProfile $user_profile
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function setUserProfile($user_profile)
	{
		$user_profile->setUser($this);
		$this->UserProfile = $user_profile;

		return $this;
	}

	/**
	 * Get UserProfile entity (one to one).
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function getUserProfile()
	{
		return $this->user_profile;
	}

	public function __sleep()
	{
		return array('id', 'username', 'password', 'open_id', 'phone', 'idCard', 'nickname', 'created_at', 'updated_at');
	}
}