<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.4 (doctrine2-annotation 3.1.3) on 2021-07-15 13:44:59.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

namespace WeiXin\Entity\Mapping;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * WeiXin\Entity\Mapping\UserProfile
 *
 * @ORM\Entity(repositoryClass="WeiXin\Entity\Repositories\UserProfileRepository")
 * @ORM\Table(name="user_profile", indexes={@ORM\Index(name="fk_user_profile_users_idx", columns={"user_id"})})
 */
class UserProfile
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	protected $id;

	/**
	 * @ORM\Column(type="integer")
	 */
	protected $user_id;

	/**
	 * @ORM\Column(type="string", length=45, nullable=true)
	 */
	protected $address;

	/**
	 * @Gedmo\Timestampable(on="create")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $created_at;

	/**
	 * @Gedmo\Timestampable(on="update")
	 * @ORM\Column(type="integer", nullable=true)
	 */
	protected $updated_at;

	/**
	 * @ORM\OneToOne(targetEntity="WeiXin\Entity\Mapping\User", inversedBy="user_profile")
	 * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
	 */
	protected $users;

	public function __construct()
	{
	}

	/**
	 * Set the value of id.
	 *
	 * @param int $id
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setId($id)
	{
		$this->id = $id;

		return $this;
	}

	/**
	 * Get the value of id.
	 *
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of user_id.
	 *
	 * @param int $user_id
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setUserId($user_id)
	{
		$this->user_id = $user_id;

		return $this;
	}

	/**
	 * Get the value of user_id.
	 *
	 * @return int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Set the value of address.
	 *
	 * @param string $address
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setAddress($address)
	{
		$this->address = $address;

		return $this;
	}

	/**
	 * Get the value of address.
	 *
	 * @return string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Set the value of created_at.
	 *
	 * @param int $created_at
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setCreatedAt($created_at)
	{
		$this->created_at = $created_at;

		return $this;
	}

	/**
	 * Get the value of created_at.
	 *
	 * @return int
	 */
	public function getCreatedAt()
	{
		return $this->created_at;
	}

	/**
	 * Set the value of updated_at.
	 *
	 * @param int $updated_at
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setUpdatedAt($updated_at)
	{
		$this->updated_at = $updated_at;

		return $this;
	}

	/**
	 * Get the value of updated_at.
	 *
	 * @return int
	 */
	public function getUpdatedAt()
	{
		return $this->updated_at;
	}

	/**
	 * Set User entity (one to one).
	 *
	 * @param \WeiXin\Entity\Mapping\User $users
	 *
	 * @return \WeiXin\Entity\Mapping\UserProfile
	 */
	public function setUser($users)
	{
		$this->users = $users;

		return $this;
	}

	/**
	 * Get User entity (one to one).
	 *
	 * @return \WeiXin\Entity\Mapping\User
	 */
	public function getUser()
	{
		return $this->users;
	}

	public function __sleep()
	{
		return array('id', 'user_id', 'address', 'created_at', 'updated_at');
	}
}