<?php

namespace WeiXin\Entity\Repositories;

use Polymer\Repository\Repository;

/**
 * ResourceManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceManagementRepository extends Repository
{
}
