<?php

namespace WeiXin\Entity\Repositories;

/**
 * ResourceManagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceManagementRepository extends \Doctrine\ORM\EntityRepository
{
}
