<?php

namespace WeiXin\Entity\Repositories;

use Polymer\Repository\Repository;

/**
 * ScenicSpotAreaRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenicSpotAreaRelationRepository extends Repository
{
}
