<?php

namespace WeiXin\Entity\Repositories;

/**
 * ScenicSpotPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenicSpotPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
