<?php

namespace WeiXin\Entity\Repositories;

/**
 * ScenicAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenicAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
