<?php

namespace WeiXin\Entity\Repositories;

/**
 * ScenicSpotAreaRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenicSpotAreaRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
