<?php

namespace WeiXin\Entity\Repositories;

use Polymer\Repository\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends Repository
{
}
